services:
  - type: web
    name: fastapi-ml-app
    env: docker
    plan: free
    repo: https://github.com/<your-username>/<repo-name>
    branch: main
    region: oregon
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    autoDeploy: true
